### ISSUE TITLE
Using prepared statements

### ISSUE THREAD

**Issue by diasbruno** [sirherrbatka/vellum-postmodern#1]
First, really enjoy all 'vellum-*' packages!

It would be nice to be able to use prepared statements

```common-lisp
(vellum:copy-from :postmodern
  '(:select 'a.b 'a.c
    :from 'a
    :where (:and (:= 'a.b '$1) (:not 'a.c '$2))) ;; <- 
  :columns '(b c)
  :query-values '(1 "ok") ;; <- 
)
```

Not sure if this is the best way to do it, or, if it would cause problems with `vellum:copy-from`.

Let me know if you have any thoughts on this. 

I can try to make a PR.

**Comment by sirherrbatka** [comment]
Hi @diasbruno I will have to read up on the postmodern manual on how to handle this because, honestly, I have no idea right now. What I usually do is to use good old `(:select ,column-name :from ,table-name) and that works, although is not efficient I guess.

**Comment by sirherrbatka** [comment]
https://sites.google.com/site/sabraonthehill/postmodern-examples/postmodern-parametized-statements

Ok, this does not seem to be overly complex, but I would say that defprepared seems to be a more common/useful use case. What do you think?

**Comment by diasbruno** [comment]
It's something nice because it can translate the type into the sql representation on the query. Like:

```lisp 
(postmodern:query (:select 'a :from 'b :where (:= 'b.id '$1)) 1)
```

**Comment by diasbruno** [comment]
Exactly.

**Comment by diasbruno** [comment]
My question is if you have a better way to pass these values down to `copy-from` that wouldn't be weird in other cases. 
Not sure it passing something like `:query-values '(1 "ok")` would be the best way.

**Comment by sirherrbatka** [comment]
Passing :query-values is exactly what I would do.

**Comment by sirherrbatka** [comment]
I mean, that's why just slapped &allow-other-keys on the defgeneric of copy-from, and copy-from :csv supports a bunch of extra options like for instance :skip-whitespace. It you want to implement it, sure go ahead. Adding vellum-postmodern:defprepared macro also sounds a like a cool idea to me.

**Comment by sirherrbatka** [comment]
Ok, so what we are doing? Wanna finish this up or perhaps you want me to take over?

**Comment by diasbruno** [comment]
I'm currently busy with other stuff. If you can take that PR and finish it, please do.

**Comment by sirherrbatka** [comment]
I will take a look on the weekend. thx for your code.

**Comment by diasbruno** [comment]
Sure. Thanks for helping me with that PR. 
I use this project everyday, so hope to contribute more soon.

**Comment by sirherrbatka** [comment]
Oh, how awesome is that. :-) Happy to see my stuff being usefull.

**Comment by sirherrbatka** [comment]
This took longer than expected, but I finally found some time. I think that the simplest way is the most appropriate here so I just decided that the user ought to pass the name as the query and t as :prepared. Query should be prepared before executing, and I see no benefit in wrapping cl-postgres in that respect. I still have to test my solution.

**Comment by diasbruno** [comment]
Nice. I wrapped in this package just so people wouldn't need to learn cl-postgres. 
Looks great this solution tough.

**Comment by sirherrbatka** [comment]
Well, I suspect that this could be done better but frankly specifics of how postmodern manages prepared statements confuse me.
